---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Kerberos client packages
  package:
    name: "{{ item }}"
  with_items: "{{ krb_packages_client }}"

- name: Install Kerberos client config file
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644

- name: Ensure log location exists
  file:
    path: "{{ krb_client_dir_log }}"
    state: directory
    owner: root
    group: root
    mode: 0750
